Achievement recording fixes
NetHack/NetHack pull request #34
Opened 2017-05-06 09:07 UTC by NHTangles

This properly fixes the issues with mines and soko achievement recording, as follows:
1. record_achieve_special is mapped to corpsenm, which has a default value of -1.  Setting to 1 on the prize item and then checking for nonzero will always mark the achievement (current workaround is to also check the level at pickup time, but this has other issues outlined below).
2. only checking level and otyp when setting record_achieve_special opens the possibility that a random luckstone may be generated at mine-end, and this may be interpreted as the prize (this has possibly happened though it's hard to be conclusive as monsters pick things up and move them)
3. checking the level at pickup time is problematic if a monster picks up the prize and takes it to another level before the hero gets his hands on it (cases of this have been recorded).

2017-05-06 17:24 UTC, FredrIQ commented
What if the player picks up the luckstone, walks somewhere else, and is killed, and someone else finds the bones? Wouldn't your fixes make the achievement count for them? Your changes doesn't seem to address this (bones.c isn't changed)

2017-05-07 02:28 UTC, NHTangles commented
Thanks for looking, FIQ.
This case is taken care of in invent.c - The player picks up the object, the achievement is recorded, and then the record_achieve_special flag is zeroed, so the object no longer has any special significance to the player, or any subsequent players that find it in bones.

2017-05-08 11:14 UTC, NHTangles commented
After further discussion with FIQ, it would indeed be possible for a prize item to get to another level without the player picking it up (eg by a pet or another monster) and potentially be left in bones.  Added another commit just now to address this.

2017-11-14 02:02 UTC, Xaleth requested changes
Remove unnecessary space in line 185 in bones.c

2017-11-14 02:16 UTC, NHTangles commented
Closing this because the issues have been otherwise addressed in the following commits:
58477b33f4e797fab8c8e5202e146a678de448d5
5a50bb64451196433380cd70a884f7791ce2a288

2017-11-14 02:16 UTC, closed without merging